apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerts
data:
  alerting-rules.yaml: |
    apiVersion: 1
    contactPoints:
      - name: EmailAlerts
        receivers:
          - uid: "email_uid"
            type: email
            settings:
              addresses: bermetalymkulova55@gmail.com
              singleEmail: false
            disableResolveMessage: false
    groups:
      - orgId: 1
        name: group_1m
        folder: TestFolder
        interval: 1m
        rules:
          - uid: high_cpu_usage_uid
            title: High CPU Usage Alert
            condition: A
            data:
              - refId: A
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: prometheus_uid
                model:
                  expr: (sum(rate(node_cpu_seconds_total{mode!="idle"}[5m])) by (instance) 
                        / sum(rate(node_cpu_seconds_total[5m])) by (instance) * 100) > 80
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: A
            for: 1m
            annotations:
              summary: "High CPU Usage Detected"
              description: "CPU usage is above 80% on instance {{ $labels.instance }}"
            labels:
              severity: critical
              monitor: cpu_alert
            notification_settings:
              receiver: EmailAlerts

          - uid: high_memory_usage_uid
            title: High Memory Usage Alert
            condition: A
            data:
              - refId: A
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: prometheus_uid
                model:
                  expr: ((1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100) > 80
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: A
            for: 1m
            annotations:
              summary: "High Memory Usage Detected"
              description: "Memory usage is above 80% on instance {{ $labels.instance }}"
            labels:
              severity: critical
              monitor: memory_alert
            notification_settings:
              receiver: EmailAlerts