name: Deploy Jenkins
on:
  push:
    branches:
      - main
      - task_4
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  JENKINS_VERSION: "2.387.1"  # Specify Jenkins version

jobs:
  deploy-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Set up kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}  # Ensure your kubeconfig is stored as a GitHub secret
        run: |
          echo "${KUBE_CONFIG}" > $HOME/.kube/config
          kubectl config use-context default  # Change if your context is different

      - name: Deploy Jenkins using Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash  # Install Helm
          helm repo add jenkins https://charts.jenkins.io
          helm repo update
          helm install jenkins jenkins/jenkins --namespace jenkins --create-namespace --set serviceType=NodePort  # Use NodePort or ClusterIP

      - name: Verify Jenkins Deployment
        run: |
          kubectl get pods -n jenkins
          kubectl get svc -n jenkins
