name: Terraform

on:
  push:
    branches:
      - main
      - task_1
  pull_request:
    branches:
      - main
      - task_1

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Format Terraform
        run: terraform fmt -check

  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init and Plan
        run: |
          terraform init
          terraform plan

  terraform-apply:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init and Apply
        run: |
          terraform init
          terraform apply -auto-approve

